In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/car_price_dataset.csv")
df

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5,8501
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3,12092
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2,11171
3,Audi,Q5,2023,2.0,Electric,Manual,160971,2,1,11780
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3,2867
...,...,...,...,...,...,...,...,...,...,...
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4,8884
9996,Chevrolet,Impala,2002,1.4,Electric,Automatic,168000,2,1,6240
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866
9998,Ford,Explorer,2002,1.4,Hybrid,Automatic,225772,4,1,4084
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3,3342

In [ ]:
 #1. What is the average price of all cars in the dataset?
#ANS:-
df['Price'].mean()
print(f"The average price of all cars in the dataset is ${round(df['Price'].mean(),2)}")

The average price of all cars in the dataset is $8852.96

In [11]:
#2. Which car brand has the highest average price?
#ANS:-
Brand=df.groupby("Brand")["Price"].mean().idxmax()
print(f"this is the car brand with highest average price is {Brand}")

this is the car brand with highest average price is Chevrolet

In [12]:
#3. What is the most common fuel type in the dataset?
#ANS:-
fuel=(df["Fuel_Type"].mode()[0])
print(f"this is the most common fuel type in the dataset is {fuel}")

this is the most common fuel type in the dataset is Electric

In [13]:
# 4. How many cars have a mileage greater than 200,000?
#ANS:-
len=(df[df["Mileage"] > 200000].shape[0])
print(f"Number of cars greater average than 200000 is: {len}")

Number of cars greater average than 200000 is: 3290

In [15]:
# 5. What is the distribution of cars by transmission type?
#ANS:-
Transmission = df["Transmission"].value_counts()
print(f"distribution of cars by transmission type is:\n{Transmission}")

distribution of cars by transmission type is:
Transmission
Manual            3372
Automatic         3317
Semi-Automatic    3311
Name: count, dtype: int64

In [16]:
# 6. Which car model has the highest price?
#ANS:-
car = df.loc[df["Price"].idxmax(),"Model"]
print(f"this is the car model with highest price is {car}")

this is the car model with highest price is Corolla

In [17]:
# 7. What is the average price of cars by fuel type?
#ANS:-
average_price=df.groupby("Fuel_Type")["Price"].mean()
print(f"average price of cars by fuel type is:\n{average_price}")

average price of cars by fuel type is:
Fuel_Type
Diesel       8117.336385
Electric    10032.220190
Hybrid       9113.030167
Petrol       8070.561826
Name: Price, dtype: float64

In [19]:
# 8. How many cars are from the year 2020 or later?
#ANS:-
cars= df[df['Year'] >= 2020].shape[0]
print(f"this is the number of cars are from the year 2020 or later is {cars}")

this is the number of cars are from the year 2020 or later is 1651

In [21]:
# 9. What is the average engine size for each brand?
#ANS:-
average_engine= [df.groupby("Brand")["Engine_Size"].mean()]
print(f"average engine size for each brand is:\n{average_engine}")

average engine size for each brand is:
[Brand
Audi          3.032948
BMW           2.976877
Chevrolet     2.993719
Ford          3.044275
Honda         2.925966
Hyundai       2.936683
Kia           3.053791
Mercedes      3.069745
Toyota        2.961443
Volkswagen    3.011078
Name: Engine_Size, dtype: float64]

In [48]:
# 10. Which car has the lowest mileage?
#ANS:-
lowest_mileage=df.loc[df["Mileage"].idxmin(),"Model"]
mileage=df["Mileage"].min()
print(f"this is the car with lowest mileage is {lowest_mileage}")
print(f"this is the mileage of car is {mileage}")

this is the car with lowest mileage is Explorer
this is the mileage of car is 25

In [24]:
# 11. What is the correlation between mileage and price?
#ANS:-
correlation = df['Mileage'].corr(df['Price'])
print(f"this is the correlation between mileage and price is {correlation}")

this is the correlation between mileage and price is -0.5512271827629014

In [25]:
# 12. How many cars have more than 2 owners?
#ANS:-
len = df[df['Owner_Count'] > 2].shape[0]
print(f"this is the number of cars have more than 2 owners is {len}")

this is the number of cars have more than 2 owners is 5944

In [26]:
# 13. What is the average price of cars by year?
#ANS:-
average_price= df.groupby('Year')['Price'].mean()
print(f"average price of cars by year is:\n{average_price}")

average price of cars by year is:
Year
2000     5393.735369
2001     5904.064039
2002     5956.751082
2003     6225.834646
2004     6330.725888
2005     6943.037123
2006     7249.961446
2007     7632.513953
2008     7728.418848
2009     8083.917293
2010     8503.419954
2011     8622.855234
2012     9011.446224
2013     9114.208531
2014     9587.455635
2015     9896.774648
2016    10177.600000
2017    10343.757506
2018    10939.192941
2019    11132.722090
2020    11495.284337
2021    11637.813299
2022    12067.690176
2023    12169.470982
Name: Price, dtype: float64

In [ ]:
# 14. Which car has the highest number of doors?
#ANS:-
df[df['Doors'] == df['Doors'].max()]

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Price
14,Volkswagen,Golf,2003,2.4,Petrol,Automatic,145921,5,2,5981
16,Hyundai,Elantra,2017,2.9,Electric,Automatic,38133,5,2,14837
22,Toyota,RAV4,2003,2.0,Electric,Manual,136662,5,4,6266
26,Audi,A3,2022,3.3,Electric,Manual,79350,5,3,14413
27,BMW,3 Series,2017,2.3,Electric,Semi-Automatic,142701,5,3,10645
...,...,...,...,...,...,...,...,...,...,...
9978,Mercedes,E-Class,2002,4.5,Diesel,Semi-Automatic,145363,5,2,6292
9979,Mercedes,C-Class,2012,4.3,Diesel,Automatic,51674,5,2,12466
9983,Mercedes,E-Class,2022,3.2,Petrol,Automatic,92823,5,4,13543
9991,Mercedes,E-Class,2017,1.1,Diesel,Automatic,179286,5,1,8214
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1,9866

In [28]:
# 15. What is the average mileage for each fuel type?
#ANS:-
average_mileage = df.groupby("Fuel_Type")["Mileage"].mean()
print(f"The average mileage for each fuel type is:\n{average_mileage}")

The average mileage for each fuel type is:
Fuel_Type
Diesel      150261.533041
Electric    151059.307429
Hybrid      145577.587036
Petrol      149917.694606
Name: Mileage, dtype: float64

In [29]:
# 16. How many cars are from the brand 'Toyota'?
#ANS:-
cars= df[df["Brand"] == "Toyota"].shape[0]
print(f"this is the number of cars are from the brand 'Toyota' is {cars}")

this is the number of cars are from the brand 'Toyota' is 970

In [30]:
# 17. What is the average price of cars with automatic transmission?
#ANS:-
average_price = df[df["Transmission"] == "Automatic"]["Price"].mean()
print(f"average price of cars with automatic transmission is ${round(average_price,2)}")

average price of cars with automatic transmission is $9938.25

In [50]:
# 18. Which car has the highest owner count?
#ANS:-
car=df.loc[df["Owner_Count"].idxmax(),"Model"]
owner=df["Owner_Count"].max()
print(f"this is the car with highest owner count is {car}")
print(f"this is the owner count of car is {owner}")

this is the car with highest owner count is Rio
this is the owner count of car is 5

In [34]:
# 19. What is the average engine size for cars with diesel fuel type?
#ANS:-
average_engine=df[df["Fuel_Type"] == "Diesel"]["Engine_Size"].mean()
print(f"average engine size for cars with diesel fuel type is {round(average_engine,2)}")

average engine size for cars with diesel fuel type is 3.01

In [33]:
# 20. How many cars have a price greater than $10,000?
#ANS:-
cars = df[df['Price'] > 10000 ].shape[0]
print(f"The number of cars with a price greater than $10,000 is {cars}")

The number of cars with a price greater than $10,000 is 3651